name: BodyMax
options:
  bundleIdPrefix: com.moundai
  deploymentTarget:
    iOS: 16.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

targets:
  BodyMax:
    type: application
    platform: iOS
    sources:
      - path: BodyMax
    settings:
      base:
        INFOPLIST_FILE: BodyMax/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moundai.bodymax
        DEVELOPMENT_TEAM: GN2N584376  # Leave this empty for automatic team selection
    info:
      path: BodyMax/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: We need camera access to take your progress photos for analysis
        NSPhotoLibraryUsageDescription: We need access to your photos to select progress photos for analysis
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true